name: Task
description: chores, tooling, content, sub-issues of an epic
type: Task

body:
  - type: textarea
    id: what
    attributes:
      label: what
      description: what needs doing
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: todo
      value: |
        - [ ]
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: notes
    validations:
      required: false
